spring.application.name=resena


# Conexión a la base de datos (Note que el esquema cambia a 'resenas_db')
spring.datasource.url=jdbc:mysql://localhost:3306/resenas_db
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor distinto al de juegos
server.port=8082