spring.application.name=resena


# Conexión a la base de datos (Note que el esquema cambia a 'resenas_db')
spring.datasource.url=jdbc:mysql://localhost:3306/resenas_db
spring.datasource.username=root
spring.datasource.password=root

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8082

# Arregla error de versiones en archivo POM
spring.cloud.discovery.enabled=false

#URL SWAGGER
#http://localhost:8082/swagger-ui/index.html

#Para forzar que el sistema lea archivos sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.cloud.openfeign.circuitbreaker.enabled=true