# Da un nombre a la aplicación para que el sistema la identifique.
spring.application.name=moderacion

# Define la ruta de conexión a la base de datos exclusiva de este microservicio.
# Debe crear el esquema "moderacion_db" en su MySQL antes de iniciar la aplicación.
spring.datasource.url=jdbc:mysql://localhost:3306/moderacion_db

# Usuario y contraseña de su motor de base de datos local.
spring.datasource.username=root
spring.datasource.password=root

# Instruye a Spring para que cree las tablas automáticamente al iniciar el proyecto 
# y las borre al detenerlo. Es una configuración pensada para entornos de prueba.
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra en la terminal (consola) las consultas SQL que se ejecutan internamente, 
# dándoles un formato fácil de leer. Útil para buscar errores.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especifica el "dialecto" exacto para que el sistema traduzca correctamente 
# las instrucciones de Java al lenguaje que entiende MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Asigna un puerto de red único. Si Juegos usa el 8081 y Reseñas el 8082, 
# asignamos el 8083 para que los tres puedan funcionar al mismo tiempo sin chocar.
server.port=8083