spring.application.name=gestion-usuarios
spring.profiles.active=test

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
server.port = 8082

# Habilita la ejecución de scripts SQL en bases de datos externas como MySQL
spring.sql.init.mode=always

# Asegura que Hibernate cree las tablas antes de ejecutar el script de datos
spring.jpa.defer-datasource-initialization=true

#URL Swagger
#http://localhost:8082/swagger-ui/index.html